### PR TITLE
React capstone project - Metrics webapp

### PR DESCRIPTION
**Pull request by normainobary2021**
Description
This React capstone project is about building a mobile web application to check a list of metrics you will create using React and Redux.

General requirements

- There are no linter errors.
- I used the correct Gitflow.
- I documented my work.
- HTML/CSS & JavaScript requirements are met.

Project requirements:

- Used coin stats API.
- Create react app.
- Used redux.
- Used iconscout.
- Styled the app for mobile first.

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Norman, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Nice job acknowledging Nelson Sakwa on Behance for the [Original design idea](https://www.behance.net/sakwadesignstudio).
- Correctly deployed project
- API fetch properly implemented
- State management with Redux properly implemented
- Navigation working as intended
- Filter works great! 
- Great ReadMe

## Required Changes ♻️
Video presentation for this project is missing 😞 Kindly ensure to record a maximum of 5 minutes video presenting the features of the project. The recorded video should:
- [ ]  entail the **features** of the project.
- [ ] have a maximum length of **5 minutes**.
- [ ] be **clear and objective description** about the project in professional English. The topic and purpose of the project are made clear.
- [ ] contains a demo of the project, highlighting all the project features.
- [ ] contain a highlight about a piece of the code the student finds interesting or is proud of making. 💪 

- [ ] Your coins list on mobile screen appears overlapping. Kindly ensure that cells on each row of the dual columns are on the same line.

**Your design:**        |  **The original design:**
:-------------------------:|:-------------------------:
Home Page | Home Page

A test case is failing. Your cases do not test for several component of your app.
- [ ] Kindly ensure that all test cases pass.
- [ ] Kindly add test cases for several components and features implemented on your app.

**Failing test:**
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

**You can also consider:**
- Kindly ensure that the _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 
- I think you should change the header title _Authors_ to _Author_ in your ReadMe, as this project is worked on by a sole contributor.
- MIT license link in your ReadMe is broken, kindly endeavor to fix it, and remove guide note below it.

Implementing the above change(s) will make your ReadMe/ repository stand out even better 😉

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by normainobary2021** [comment]
Thank you @rloterh for the review. I have made all the necessary changes.

**Review by nicupop729 — CHANGES_REQUESTED** [review]
Hi @normainobary2021 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Highlights
 - [X] Linters are passing :heavy_check_mark:
 - [X] Good presentation video :heavy_check_mark:  


 ## Required Changes ♻️
- Kindly add the tests for your project as required in the project requirements and by the previous reviewer.
image

At the moment even your snapshot tests are doing the same thing, only the description of the test is different.
image

- [ ] Kindly make sure that you create unit tests for pure functions in your Redux code.
- [ ] Create integration tests for your application using the React Testing Library.
 - You may need to mock the access to the API, so that your tests don't send actual requests.
 - You may need to mock the connection to the Redux Store.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by normainobary2021** [comment]
Thank you @nicupop729 
I hope I have made satisfactory changes

**Review by nicupop729 — APPROVED** [review]
Hi @normainobary2021,

### This is a manual review 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by normainobary2021** [comment]
Thank you so much @nicupop729 I am thrilled to hear this..

**Pull request merged**
